### ISSUE TITLE
A hyphen is not allowed in module names

### ISSUE THREAD

**Issue by kseistrup** [cursusdb/cursusdb-py#1]
```py
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cursusdb-py
  File "<stdin>", line 1
    import cursusdb-py
                   ^
SyntaxError: invalid syntax
>>>
```

While the hyphen could be replaced with an underscore, why not drop the `-py` altogether? When we use this module we already know that we are on a Python platform, so the `-py` is redundant. It's easy to type just `cursusdb`, and I can't see the need for further disambiguation:

```py
from cursusdb import Client
```

**Comment by guycipher** [comment]
@kseistrup I agree.  I am fixing that now.  The repo name gotta stay the same because dupes haha!

**Comment by guycipher** [comment]
@kseistrup https://github.com/cursusdb/cursusdb-py/commit/28a2ea7d1ef495d3da5f2ae68d364dcd8d3c3b04
Committed.  I am working on deploying to PyPi and will update docs accordingly.  Thank you for the issue!!
